### ISSUE TITLE
Website crash due to invalid substat

### ISSUE THREAD

**Issue by frzyc** [Nekodigi/genshin-score-simulator#2]
Tried to scan in an artifact with an invalid substat:
<img width="505" alt="image" src="https://user-images.githubusercontent.com/1754901/221399525-b822dc36-a1eb-4f6b-bbbb-ccc33f4fdf0e.png">

<img width="302" alt="image" src="https://user-images.githubusercontent.com/1754901/221399489-c61a668a-2d3b-4a13-8572-0ea044541479.png">

![image](https://user-images.githubusercontent.com/1754901/221399519-87add3c4-f606-4766-8ca4-e29c1c075556.png)

<img width="541" alt="image" src="https://user-images.githubusercontent.com/1754901/221399512-b736636a-71be-43ed-b504-4441f09cdfd7.png">

Needed to delete the LocalStorage entry to recover the site.

**Comment by Nekodigi** [comment]
Thank you for your feedback!
I've seen this issue but I didn't know the reason.
Thanks to your information I could solve this issue.

- strToArtifact.ts
The scanned value sometimes contains unnecessary text, so I added some filters.
```typescript
var value_ = str.includes("%")
    ? datas[1].split("%")[0].replaceAll("%", "").replaceAll(" ", "")
    : datas[1]; //10% => 10
```

The NaN value possibly causes a problem so I changed to set the value 0 and confidence 0.
```typescript
  let value = Number(value_);
  if (isNaN(value)) {
    console.log("NaN", value_, key_, str);
    value = 0;
    maxSim = 0;
  }
```

- StatIcon.tsx
The value should not be displayed when the value is null, and that was causing the problem.
``` typescript
if (value !== undefined && value !== null) {
    if (text.charAt(text.length - 1) === "%") {
      text = text.slice(0, -1);
      text += `+${value.toFixed(1)}%`;
    } else {
      text += `+${value.toFixed(0)}`;
    }
  }
```
